# Generated by Django 3.2.12 on 2023-01-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_vagas_email'),
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taref',
            new_name='Tarefa',
        ),
    ]
