# Generated by Django 4.1.5 on 2023-01-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nicho_mercado',
            field=models.CharField(choices=[('PB', 'Programador | Back-end'), ('PF', 'Programador | Font-end'), ('FS', 'FullStack'), ('M', 'Marketing'), ('N', 'Nutrição'), ('D', 'Design')], max_length=3),
        ),
    ]
