# Generated by Django 4.1.7 on 2023-04-01 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_cep_alter_empresa_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vagas',
            name='contratacao',
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nicho_mercado',
            field=models.CharField(choices=[('PB', 'Programador | Back-end'), ('PF', 'Programador | Font-end'), ('FS', 'FullStack'), ('M', 'Marketing'), ('D', 'Design'), ('G', 'Gerente')], max_length=3),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='nivel_experiencia',
            field=models.CharField(choices=[('TE', 'Trainee/Estagiário'), ('J', 'Júnior'), ('P', 'Pleno'), ('S', 'Sênior'), ('E', 'Especialista'), ('L', 'Líder')], max_length=2),
        ),
    ]
