# Generated by Django 4.1.7 on 2023-04-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_empresa_cnpj_vagas_contratacao_alter_empresa_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologias',
            name='logo_tecn',
            field=models.ImageField(null=True, upload_to='logo_tecn'),
        ),
    ]
