# Generated by Django 4.1.7 on 2023-04-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_tecnologias_logo_tecn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nicho_mercado',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nicho_empresa',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
