# Generated by Django 4.1.7 on 2023-04-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_nicho_remove_empresa_nicho_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_tecn', models.ImageField(null=True, upload_to='logo_tecn')),
                ('profissao', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nicho_empresa',
        ),
        migrations.DeleteModel(
            name='Nicho',
        ),
        migrations.AddField(
            model_name='empresa',
            name='profissao_empresa',
            field=models.ManyToManyField(to='empresa.profissao'),
        ),
    ]
