# Generated by Django 4.1.7 on 2023-04-10 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_rename_logo_tecn_profissao_logo_profissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissao',
            options={'verbose_name': 'Profissao', 'verbose_name_plural': 'Profissoes'},
        ),
        migrations.RenameField(
            model_name='vagas',
            old_name='tecnologias_estudar',
            new_name='tecnologia_vaga',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='tecnologias_dominadas',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='titulo',
        ),
        migrations.AddField(
            model_name='vagas',
            name='data_inicial',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='vagas',
            name='profissao_vaga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.profissao'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='remuneracao_profissional',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vagas',
            name='trabalho',
            field=models.CharField(choices=[('P', 'Presencial'), ('H', 'Híbrido'), ('R', 'Remoto')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vagas',
            name='contratacao',
            field=models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ')], max_length=3),
        ),
    ]
